from selenium.webdriver.common.by import By

class Locators:
    ORDERS = (By.XPATH, "// *[text() = 'Лента Заказов']")
    FIRST_ORDER_SELECTION = (By.XPATH, "//li[@class ='OrderHistory_listItem__2x95r mb-6']")
    SOSTAV = (By.XPATH, "// *[text() = 'Cостав']")
    ORDER_ID = (By.XPATH, "//p[@class ='text text_type_digits-default']")
    TOTAL_ORDERS = (By.XPATH, "// *[text() = 'Выполнено за все время:']/following-sibling::p")
    TODAY_ORDERS = (By.XPATH, "// *[text() = 'Выполнено за сегодня:']/following-sibling::p")
    ORDERS_HISTORY = (By.XPATH, "// *[text() = 'История заказов']")
    LK_BUTTON = (By.XPATH, "// *[text() = 'Личный Кабинет']")
    EMAIL_FIELD = (By.XPATH, "//input[@class ='text input__textfield text_type_main-default' and @name = 'name']")
    PASSWORD_FIELD = (By.XPATH, "//input[@class ='text input__textfield text_type_main-default' and @name = 'Пароль']")
    ENTER_BUTTON = (By.XPATH, "// *[text() = 'Войти']")
    ORDERS_HISTORY_HIGHLIGHTED = (By.XPATH, "//a[@class ='Account_link__2ETsJ text text_type_main-medium text_color_inactive Account_link_active__2opc9']")
    LOGOUT_BUTTON = (By.XPATH, "// *[text() = 'Выйти']")
    ENTER_LABEL = (By.XPATH, "// *[text() = 'Вход']")
    CONSTRUCTOR = (By.XPATH, "// *[text() = 'Конструктор']")
    COMBINE_BURGER = (By.XPATH, "// *[text() = 'Соберите бургер']")
    INGREDIENT_DETAILS = (By.XPATH, "// *[text() = 'Детали ингредиента']")
    SHINE_BULKA = (By.XPATH, "// *[text() = 'Флюоресцентная булка R2-D3']")
    MAKE_ORDER = (By.XPATH, "// *[text() = 'Оформить заказ']")
    ORDER_CREATED = (By.XPATH, "// *[text() = 'идентификатор заказа']")
    ORDER_PLACE = (By.XPATH, "//div[@class ='constructor-element constructor-element_pos_top']")
    PRICE = (By.XPATH, "//p[@class ='text text_type_digits-medium mr-3']")
    CLOSE_DETAILS = (By.XPATH, "//button[@class ='Modal_modal__close_modified__3V5XS Modal_modal__close__TnseK']")